import type { Metadata } from "next";
import { Montserrat as Inter } from "next/font/google";
import "./globals.css";
import NavMain from "./components/NavMain/NavMain";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavMain />
        {children}
      </body>
    </html>
  );
}
